url: "https://michalruprecht.com"
baseurl: ""

title: Michal Ruprecht Official Website
site.title: Michal Ruprecht Official Website

description: Michal Ruprecht is a health journalist and medical student.

name: Michal T. Ruprecht Official Website

markdown: kramdown

author:
  name: Michal T. Ruprecht

url-pretty: "michalruprecht.com"

gtag: "'config', 'UA-141229929-1'"
google_analytics: "UA-141229929-1"

# Make sure Jekyll looks in your _layouts folder
layouts_dir: _layouts

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
  - node_modules
  - vendor

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
